# Generated by Django 4.2.4 on 2023-09-25 05:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, null=True, unique=True
            ),
        ),
    ]
