# Generated by Django 4.2.4 on 2023-09-25 14:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
