# Generated by Django 4.2.4 on 2023-09-27 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_remove_order_order_date_order_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_method",
        ),
    ]
