# Generated by Django 4.2.4 on 2023-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_remove_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(
                choices=[("COD", "Cash On Delivery"), ("Razor Pay", "Razor Pay")],
                default="Cash On Delivery",
                max_length=100,
            ),
        ),
    ]
