# Generated by Django 4.2.4 on 2023-10-01 05:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_product_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0010_reviews_reviewimages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
        migrations.RenameModel(
            old_name="ReviewImages",
            new_name="ReviewImage",
        ),
    ]
