# Generated by Django 4.2.4 on 2023-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_rename_reviews_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
