# Generated by Django 4.2.4 on 2023-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_order_coupon_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
