# Generated by Django 4.2.4 on 2023-10-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dicount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
