# Generated by Django 4.2.4 on 2023-10-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderitem_dicount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='dicount',
        ),
    ]
