# Generated by Django 4.2.4 on 2023-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
