# Generated by Django 4.2.4 on 2023-10-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_order_data_orderitem_order_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_data',
            new_name='item_data',
        ),
    ]
