# Generated by Django 4.2.6 on 2023-11-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_address_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
