# Generated by Django 4.2.4 on 2023-08-20 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_rename_league_id_club_league_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="countrymodel",
            old_name="flag_image_path",
            new_name="flag_image_pat",
        ),
    ]
