# Generated by Django 4.2.4 on 2023-09-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0006_alter_countrymodel_flag_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="league_thumbnail/"),
        ),
        migrations.AlterField(
            model_name="club",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to="categories.league",
            ),
        ),
    ]
