# Generated by Django 4.2.4 on 2023-09-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0007_league_thumbnail_alter_club_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="club_thumbnail/"),
        ),
    ]
