# Generated by Django 4.2.4 on 2023-09-09 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_productitem_price_product_price"),
        ("wishlists", "0002_alter_wishlistmodel_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistmodel",
            name="product",
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wishlists.wishlistmodel",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_item",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
