# Generated by Django 4.2.4 on 2023-09-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_productitem_price_product_price"),
        ("wishlists", "0003_remove_wishlistmodel_product_wishlistitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlistitem",
            old_name="cart",
            new_name="wishlist",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="products",
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="products.product",
            ),
        ),
    ]
