# Generated by Django 4.2.4 on 2023-09-09 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_productitem_price_product_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wishlists", "0004_rename_cart_wishlistitem_wishlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistmodel",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
