# Generated by Django 4.2.4 on 2023-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_productitem_price_product_price"),
        ("wishlists", "0005_wishlistmodel_product_alter_wishlistmodel_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistmodel",
            name="product",
        ),
        migrations.AddField(
            model_name="wishlistmodel",
            name="products",
            field=models.ManyToManyField(
                related_name="wishlist_items", to="products.product"
            ),
        ),
    ]
