# Generated by Django 4.2.4 on 2023-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0006_remove_wishlistmodel_product_wishlistmodel_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlistmodel",
            old_name="products",
            new_name="product",
        ),
    ]
