# Generated by Django 4.2.4 on 2023-09-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_cartitem_cart_remove_cartitem_product_item_and_more"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="status",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_quantity",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_item",
                to="products.productitem",
            ),
        ),
    ]
