# Generated by Django 4.2.4 on 2023-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cart",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
