# Generated by Django 4.2.4 on 2023-09-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_cart_completed_cart_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="cart.cart",
            ),
        ),
    ]
