# Generated by Django 4.2.4 on 2023-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_cartitem_total_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
