# Generated by Django 4.2.4 on 2023-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_alter_cart_coupon_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="final_price",
            field=models.IntegerField(default=0),
        ),
    ]
