# Generated by Django 4.2.4 on 2023-08-12 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="mobile",
        ),
    ]
