# Generated by Django 4.2.4 on 2023-08-23 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productitem_actual_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="discount_percent",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
