# Generated by Django 4.2.4 on 2023-09-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0007_league_thumbnail_alter_club_league"),
        ("products", "0003_alter_productitem_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pro",
                to="products.productitem",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="club_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.club",
            ),
        ),
    ]
