# Generated by Django 4.2.4 on 2023-09-04 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_cart_alter_productitem_product_id_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_item",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
