# Generated by Django 4.2.4 on 2023-09-06 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_cartitem_cart_remove_cartitem_product_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productitem",
            old_name="actual_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="productitem",
            name="discount_percent",
        ),
        migrations.RemoveField(
            model_name="productitem",
            name="selling_price",
        ),
    ]
