# Generated by Django 4.2.4 on 2023-09-13 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_remove_productitem_gender_product_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="productitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=12.0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("kids", "Kids")],
                max_length=10,
            ),
        ),
    ]
