# Generated by Django 4.2.4 on 2023-09-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_remove_productitem_price_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="year",
            field=models.CharField(
                choices=[
                    ("22-23", "2022-2023"),
                    ("21-22", "2021-2022"),
                    ("20-21", "2020-2021"),
                    ("19-20", "2019-2020"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
