# Generated by Django 4.2.4 on 2023-09-13 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_product_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("type", "year")},
        ),
    ]
