# Generated by Django 4.2.4 on 2023-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_club_thumbnail"),
        ("products", "0014_alter_product_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="product",
            name="year",
            field=models.CharField(
                choices=[
                    ("23-24", "2023-2024"),
                    ("22-23", "2022-2023"),
                    ("21-22", "2021-2022"),
                    ("20-21", "2020-2021"),
                    ("19-20", "2019-2020"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("club_id", "type", "year")},
        ),
    ]
