# Generated by Django 4.2.4 on 2023-09-13 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_club_thumbnail"),
        ("products", "0015_alter_product_unique_together_alter_product_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={
                ("country_id", "type", "year"),
                ("club_id", "type", "year"),
            },
        ),
    ]
