# Generated by Django 4.2.4 on 2023-09-13 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_club_thumbnail"),
        ("products", "0016_alter_product_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={
                ("club_id", "type", "year", "gender"),
                ("country_id", "type", "year", "gender"),
            },
        ),
    ]
