# Generated by Django 4.2.4 on 2023-10-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
