# Generated by Django 4.2.4 on 2023-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
