# Generated by Django 4.2.4 on 2023-10-03 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0004_alter_coupon_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="discount_type",
        ),
    ]
